//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUShopNearby2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Propietario> Propietario { get; set; }
        public virtual DbSet<Tienda> Tienda { get; set; }
    
        public virtual ObjectResult<rptTiendaProducto_Result> rptTiendaProducto(Nullable<int> product)
        {
            var productParameter = product.HasValue ?
                new ObjectParameter("product", product) :
                new ObjectParameter("product", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptTiendaProducto_Result>("rptTiendaProducto", productParameter);
        }
    
        public virtual ObjectResult<rptPropietarioTienda_Result> rptPropietarioTienda(Nullable<int> propietario)
        {
            var propietarioParameter = propietario.HasValue ?
                new ObjectParameter("propietario", propietario) :
                new ObjectParameter("propietario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptPropietarioTienda_Result>("rptPropietarioTienda", propietarioParameter);
        }
    }
}
