//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUShopNearby2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tienda()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int idTienda { get; set; }
        public string Nombre { get; set; }
        public string R_Social { get; set; }
        public string N_Telefono { get; set; }
        public string Direccion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> idPropietario { get; set; }
        public string Categoria { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
